/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/theov4.glb')
  const { actions } = useAnimations(animations, group)
  const material = new THREE.MeshPhongMaterial({
    color:"black",
    emissive: "black",
    specular: "#ff4000",
    shininess: 100,

  })
  console.log(nodes.mum_rpmlet_midres_rig_mastermum_rpmlet_rig);
  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.mum_rpmlet_midres_rig_mastermum_rpmlet_rig} />
      <group position={[0.1, 0, 0]} rotation={[0.29, -0.69, 0.01]} scale={1.26}>
        <mesh castShadow receiveShadow geometry={nodes.vine_rod.geometry} material={material} />
      </group>
      <group position={[0, 0, -0.37]}>
        <group position={[0.06, -0.07, 0.43]} rotation={[-0.3, -0.04, 0.32]} scale={[1.22, 1.32, 1.22]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_hat_01.geometry}
            material={material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_hat_02.geometry}
            material={material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_hat_03.geometry}
            material={material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_hat_05.geometry}
            material={material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_hat_06.geometry}
            material={material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_hat_07.geometry}
            material={material}
          />
        </group>
        <group position={[0.09, 0, 0.4]} rotation={[-0.47, 0.21, 0.63]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.theo_dad_cloak_01.geometry}
            material={material}
          />
        </group>
      </group>
      <group position={[0.06, -0.09, 0]} rotation={[0.05, -0.09, 0.3]} scale={[1.84, 1.42, 1.64]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_gum_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth01_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth02_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth03_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth04_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth05_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth06_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth07_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth08_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth09_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth10_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth11_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth12_up.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_gum_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth01_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth02_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth03_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth04_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth05_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth06_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth07_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth08_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth09_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth10_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth11_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_teeth_tooth12_dwn.geometry}
          material={material}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Teethdad_hires_mod_mouth_tongue.geometry}
          material={material}
        />
      </group>
      <PerspectiveCamera
        makeDefault={false}
        far={10000}
        near={0.01}
        fov={81.2}
        position={[0.04, 0.08, 0.36]}
        rotation={[0, 0.11, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cape6.geometry}
        material={material}
        position={[0, 0.09, -0.03]}
        scale={4.53}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Theo3_Theo_Legs11.geometry}
        material={material}
      />
    </group>
  )
}

useGLTF.preload('/theov4.glb')
